export const APPEND_SIDEBAR_LEFT = 'APPEND_SIDEBAR_LEFT'
export const APPEND_SIDEBAR_RIGHT = 'APPEND_SIDEBAR_RIGHT'
export const APPEND_FOOTER = 'APPEND_FOOTER'
export const APPEND_APP_TOOL = 'APPEND_APP_TOOL'

export const TOOL_POSITION = {
  LEFT_END: 'LEFT_END',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  RIGHT_END: 'RIGHT_END'
}
