export const APPEND_SIDEBAR_LEFT = 'APPEND-SIDEBAR-LEFT'
export const APPEND_SIDEBAR_RIGHT = 'APPEND-SIDEBAR-RIGHT'
export const APPEND_FOOTER = 'APPEND-FOOTER'
export const APPEND_APP_TOOL = 'APPEND-APP-TOOL'
